/* 競プロ 5分ドリルの問題データ。⟦正解|誤答|誤答#解説⟧ が穴埋めの候補。
   sw: 入れ替えてもよい行の組 / wr: 組み立て問題にする行 / bug: [行, 間違った行, 理由] / pz: 並べ替え問題に使うか */
window.DRILL_DATA={"topics":[
{"id":"bitfull","name":"全探索と bit 全探索","lv":1,"parts":[
 {"id":"main","name":"bit 全探索","desc":"N 個の品物 A の選び方を全部試し、合計がちょうど K になる選び方を数える。",
  "py":{"lines":[
   "cnt = 0",
   "for mask in range(⟦1 << N|N << 1|2 * N|N ** 2#N 個それぞれ「選ぶ / 選ばない」で 2^N 通り。1 << N が 2^N⟧):",
   "    s = 0",
   "    for i in range(N):",
   "        if ⟦mask >> i & 1|mask & i|mask >> i|i >> mask & 1#mask の i ビット目が 1 なら、i 番目を選んでいる⟧:",
   "            s += A[i]",
   "    if s == K:",
   "        cnt += 1",
   "print(cnt)"],
   "sw":[],"wr":[1,4,5],"pz":true,
   "bug":[[1,"for mask in range(N):","range(N) では N 通りしか試せない。選び方は 2^N 通りなので 1 << N"],
          [4,"        if mask & i:","mask & i は「mask と i に共通するビット」。i ビット目を見るには mask >> i & 1"],
          [2,"    s = 1","和は 0 から足し始める"]]},
  "cpp":{"lines":[
   "int cnt = 0;",
   "for (int mask = 0; mask < ⟦(1 << N)|(N << 1)|2 * N|N * N#2^N 通り。1 << N が 2^N⟧; mask++) {",
   "    long long s = 0;",
   "    for (int i = 0; i < N; i++) {",
   "        if (⟦mask >> i & 1|mask & i|mask >> i|i >> mask & 1#mask の i ビット目が 1 なら、i 番目を選んでいる⟧) s += A[i];",
   "    }",
   "    if (s == K) cnt++;",
   "}",
   "cout << cnt << endl;"],
   "sw":[],"wr":[4,6],"pz":true,
   "bug":[[1,"for (int mask = 0; mask <= (1 << N); mask++) {","<= だと mask = 2^N まで回り、存在しない選び方を1つ余分に試してしまう"],
          [4,"        if (mask & i) s += A[i];","mask & i は「mask と i に共通するビット」。i ビット目を見るには mask >> i & 1"]]}}
]},
{"id":"binsearch","name":"二分探索","lv":1,"parts":[
 {"id":"main","name":"めぐる式の二分探索","desc":"ソート済みの配列 A で、x 以上になる最初の位置 (lower_bound) を求める。ng と ok を配列の外側から始める「めぐる式」。",
  "py":{"lines":[
   "ng, ok = ⟦-1, len(A)|0, len(A) - 1|0, len(A)|-1, len(A) - 1#両端を配列の外に置くと、全部 x 以上・全部 x 未満の場合も正しく扱える⟧",
   "while ⟦ok - ng > 1|ok > ng|ok - ng > 0|ok >= ng#ok と ng が隣り合ったら境界が決まる。幅が 2 以上ある間だけ続ける⟧:",
   "    mid = (ok + ng) // 2",
   "    if A[mid] ⟦>=|>|<=|<#x 以上の最初の位置なので >=。> にすると x より大きい最初 (upper_bound) になる⟧ x:",
   "        ⟦ok|ng#条件を満たした (A[mid] >= x) ので、ok 側を mid まで縮める⟧ = mid",
   "    else:",
   "        ng = mid",
   "print(ok)"],
   "sw":[],"wr":[1,2,3],"pz":true,
   "bug":[[1,"while ok > ng:","ok = ng + 1 になっても終わらず、mid が動かなくなって無限ループになる"],
          [3,"    if A[mid] > x:","> だと「x より大きい最初の位置」(upper_bound) になる"],
          [4,"        ok = mid + 1","めぐる式では ok も ng も mid に動かすだけ。+1 すると答えを飛び越えることがある"]]},
  "cpp":{"lines":[
   "int ng = ⟦-1|0#ng は配列の左の外側から⟧, ok = ⟦A.size()|A.size() - 1#ok は配列の右の外側から。全部 x 未満なら答えは A.size()⟧;",
   "while (⟦ok - ng > 1|ok > ng|ok - ng > 0|ok >= ng#幅が 2 以上ある間だけ続ける⟧) {",
   "    int mid = (ok + ng) / 2;",
   "    if (A[mid] ⟦>=|>|<=|<#x 以上の最初の位置なので >=⟧ x) ok = mid;",
   "    else ng = mid;",
   "}",
   "cout << ok << endl;"],
   "sw":[],"wr":[1,2,3],"pz":true,
   "bug":[[1,"while (ok > ng) {","隣り合っても終わらず、無限ループになる"],
          [3,"    if (A[mid] > x) ok = mid;","> だと x より大きい最初の位置 (upper_bound) になる"],
          [4,"    else ng = mid + 1;","ng も mid に動かすだけ。+1 すると境界を飛び越えることがある"]]}}
]},
{"id":"prefixsum","name":"累積和・いもす法","lv":1,"parts":[
 {"id":"main","name":"累積和","desc":"累積和 S を作り、A[l] + … + A[r-1] を O(1) で求める。",
  "py":{"lines":[
   "S = [0] * (⟦N + 1|N|N - 1#先頭に 0 を置くので、長さは N + 1⟧)",
   "for i in range(N):",
   "    S[i + 1] = ⟦S[i] + A[i]|S[i] + A[i + 1]|S[i - 1] + A[i]|A[i]#S[i + 1] は A[0] から A[i] までの和⟧",
   "ans = ⟦S[r] - S[l]|S[r] - S[l - 1]|S[r + 1] - S[l]|S[r - 1] - S[l]#S[r] は A[0..r-1]、S[l] は A[0..l-1] の和。引くと A[l..r-1] が残る⟧"],
   "sw":[],"wr":[2,3],"pz":true,
   "bug":[[2,"    S[i + 1] = S[i] + A[i + 1]","A[i + 1] だと 1 つずれる。S[i + 1] = S[i] + A[i]"],
          [3,"ans = S[r] - S[l - 1]","S[l - 1] を引くと A[l-1] まで入ってしまう"]]},
  "cpp":{"lines":[
   "vector<long long> S(⟦N + 1|N|N - 1#先頭に 0 を置くので、長さは N + 1⟧, 0);",
   "for (int i = 0; i < N; i++) S[i + 1] = ⟦S[i] + A[i]|S[i] + A[i + 1]|S[i - 1] + A[i]#S[i + 1] は A[0] から A[i] までの和⟧;",
   "long long ans = ⟦S[r] - S[l]|S[r] - S[l - 1]|S[r + 1] - S[l]#引くと A[l..r-1] が残る⟧;"],
   "sw":[],"wr":[1,2],"pz":true,
   "bug":[[1,"for (int i = 0; i < N; i++) S[i + 1] = S[i] + A[i + 1];","A[i + 1] だと 1 つずれる"],
          [2,"long long ans = S[r] - S[l - 1];","S[l - 1] を引くと A[l-1] まで入ってしまう"]]}},
 {"id":"imos","name":"いもす法","desc":"区間 [l, r) に v を足す操作 ops をたくさん行い、最後にまとめて反映する。",
  "py":{"lines":[
   "D = [0] * (N + 1)",
   "for l, r, v in ops:",
   "    D[l] += v",
   "    D[⟦r|r - 1|r + 1|l + 1#区間は [l, r) なので、r の位置で足した分を打ち消す⟧] -= v",
   "for i in range(N):",
   "    D[i + 1] += ⟦D[i]|D[i + 1]|D[i - 1]#前から順に足していく (累積和)⟧"],
   "sw":[[2,3]],"wr":[2,3,5],"pz":true,
   "bug":[[3,"    D[r + 1] -= v","[l, r) なので r で打ち消す。r + 1 だと 1 マス余計に足される"],
          [5,"    D[i] += D[i + 1]","累積は前から後ろへ。D[i + 1] += D[i]"]]},
  "cpp":{"lines":[
   "vector<long long> D(N + 1, 0);",
   "for (auto [l, r, v] : ops) {",
   "    D[l] += v;",
   "    D[⟦r|r - 1|r + 1#区間は [l, r) なので r で打ち消す⟧] -= v;",
   "}",
   "for (int i = 0; i < N; i++) D[i + 1] += D[i];"],
   "sw":[[2,3]],"wr":[2,3,5],"pz":true,
   "bug":[[3,"    D[r + 1] -= v;","[l, r) なので r で打ち消す"],
          [5,"for (int i = 0; i < N; i++) D[i] += D[i + 1];","累積は前から後ろへ"]]}}
]},
{"id":"twoptr","name":"尺取り法","lv":1,"parts":[
 {"id":"main","name":"尺取り法","desc":"正の数の列 A で、和が K 以下になる区間 [l, r) の個数を数える。r は左に戻らない。",
  "py":{"lines":[
   "ans, r, s = 0, 0, 0",
   "for l in range(N):",
   "    while r < N and ⟦s + A[r] <= K|s <= K|s + A[r] < K|A[r] <= K#次の A[r] を足しても K 以下なら右に伸ばす⟧:",
   "        s += A[r]",
   "        r += 1",
   "    ans += ⟦r - l|r - l + 1|r|l - r#l から始まる条件を満たす区間は [l, l+1) から [l, r) までの r - l 個⟧",
   "    if r == l:",
   "        r += 1",
   "    else:",
   "        s -= ⟦A[l]|A[r]|A[l - 1]|A[r - 1]#左端 l が抜けるので A[l] を引く⟧"],
   "sw":[],"wr":[2,5,9],"pz":true,
   "bug":[[2,"    while r < N and s <= K:","まだ足していない A[r] を考えずに伸ばすと、和が K を超える区間まで数えてしまう"],
          [5,"    ans += r - l + 1","[l, r) は r - l 個。+1 すると数えすぎる"],
          [9,"        s -= A[r]","抜けるのは左端 l の要素。A[l] を引く"]]},
  "cpp":{"lines":[
   "long long ans = 0, s = 0;",
   "int r = 0;",
   "for (int l = 0; l < N; l++) {",
   "    while (r < N && ⟦s + A[r] <= K|s <= K|s + A[r] < K|A[r] <= K#次を足しても K 以下なら伸ばす⟧) {",
   "        s += A[r];",
   "        r++;",
   "    }",
   "    ans += ⟦r - l|r - l + 1|r|l - r#[l, r) の r - l 個⟧;",
   "    if (r == l) r++;",
   "    else s -= ⟦A[l]|A[r]|A[l - 1]#左端 l が抜ける⟧;",
   "}"],
   "sw":[[0,1]],"wr":[3,7,9],"pz":true,
   "bug":[[3,"    while (r < N && s <= K) {","足した後の和を見ないと K を超える区間まで数えてしまう"],
          [7,"    ans += r - l + 1;","+1 すると数えすぎる"],
          [9,"    else s -= A[r];","抜けるのは左端 l の要素"]]}}
]},
{"id":"bfs","name":"BFS と DFS","lv":1,"parts":[
 {"id":"main","name":"グリッドの BFS","desc":"H × W のグリッド G で、(sy, sx) から各マスへの最短の歩数 dist を求める。'#' は壁。",
  "py":{"lines":[
   "dist = [[-1] * W for _ in range(H)]",
   "dist[sy][sx] = 0",
   "q = deque([(sy, sx)])",
   "while q:",
   "    y, x = q.⟦popleft|pop|append#BFS は先に入れたものから取り出す (キュー)。pop だと後から入れたものが先に出る⟧()",
   "    for dy, dx in ((1, 0), (-1, 0), (0, 1), (0, -1)):",
   "        ny, nx = y + dy, x + dx",
   "        if 0 <= ny < H and 0 <= nx < W and G[ny][nx] == '.':",
   "            if dist[ny][nx] == ⟦-1|0|1#まだ訪れていない (-1 の) マスだけ進む⟧:",
   "                dist[ny][nx] = ⟦dist[y][x] + 1|dist[y][x]|dist[ny][nx] + 1|1#1 歩進むので、今のマスの距離 + 1⟧",
   "                q.append((ny, nx))"],
   "sw":[[1,2]],"wr":[4,6,9],"pz":true,
   "bug":[[4,"    y, x = q.pop()","pop() は後から入れたものを先に取る (スタック)。最短の歩数にならない"],
          [8,"            if dist[ny][nx] == 0:","未訪問は -1。0 はスタート地点"],
          [9,"                dist[ny][nx] = dist[y][x]","1 歩進むので + 1 が必要"]]},
  "cpp":{"lines":[
   "vector<vector<int>> dist(H, vector<int>(W, -1));",
   "queue<pair<int, int>> q;",
   "dist[sy][sx] = 0;",
   "q.push({sy, sx});",
   "while (!q.empty()) {",
   "    auto [y, x] = q.⟦front|back|top#キューは先に入れたものを front で取り出す⟧();",
   "    q.pop();",
   "    for (int d = 0; d < 4; d++) {",
   "        int ny = y + dy[d], nx = x + dx[d];",
   "        if (ny < 0 || ny >= H || nx < 0 || nx >= W) continue;",
   "        if (G[ny][nx] == '#' || dist[ny][nx] ⟦!= -1|== -1|!= 0#もう訪れたマスは飛ばす⟧) continue;",
   "        dist[ny][nx] = ⟦dist[y][x] + 1|dist[y][x]|dist[ny][nx] + 1#1 歩進むので + 1⟧;",
   "        q.push({ny, nx});",
   "    }",
   "}"],
   "sw":[[1,2],[9,10]],"wr":[5,8,11],"pz":true,
   "bug":[[5,"    auto [y, x] = q.back();","back() は最後に入れた要素。キューの先頭は front()"],
          [10,"        if (G[ny][nx] == '#' || dist[ny][nx] == -1) continue;","これだと未訪問のマスを飛ばしてしまう。飛ばすのは訪問済み (!= -1)"],
          [11,"        dist[ny][nx] = dist[y][x];","1 歩進むので + 1 が必要"]]}}
]},
{"id":"dp","name":"動的計画法 (DP)","lv":2,"parts":[
 {"id":"main","name":"ナップサック DP","desc":"重さ wt[i]・価値 val[i] の品物 N 個から、重さの合計 W 以下で価値の合計の最大を求める。",
  "py":{"lines":[
   "dp = [[0] * (W + 1) for _ in range(N + 1)]",
   "for i in range(N):",
   "    for w in range(W + 1):",
   "        dp[i + 1][w] = ⟦dp[i][w]|0|dp[i + 1][w - 1]#まず「i 番目を選ばない」場合を入れておく⟧",
   "        if w >= wt[i]:",
   "            dp[i + 1][w] = max(dp[i + 1][w], ⟦dp[i][w - wt[i]] + val[i]|dp[i][w] + val[i]|dp[i + 1][w - wt[i]] + val[i]|dp[i][w - wt[i]]#i 番目を選ぶなら、重さ wt[i] ぶん軽い状態に val[i] を足す⟧)",
   "print(dp[N][W])"],
   "sw":[],"wr":[3,4,5],"pz":true,
   "bug":[[3,"        dp[i + 1][w] = 0","選ばない場合の値を引き継がないと、前の品物までの結果が消える"],
          [4,"        if w > wt[i]:","w == wt[i] のときも選べる。>= にする"],
          [5,"            dp[i + 1][w] = max(dp[i + 1][w], dp[i + 1][w - wt[i]] + val[i])","dp[i + 1] から遷移すると、同じ品物を何度も選べてしまう (個数制限なしのナップサックになる)"]]},
  "cpp":{"lines":[
   "vector<vector<long long>> dp(N + 1, vector<long long>(W + 1, 0));",
   "for (int i = 0; i < N; i++) {",
   "    for (int w = 0; w <= W; w++) {",
   "        dp[i + 1][w] = ⟦dp[i][w]|0|dp[i + 1][w - 1]#まず「選ばない」場合を入れておく⟧;",
   "        if (w >= wt[i]) dp[i + 1][w] = max(dp[i + 1][w], ⟦dp[i][w - wt[i]] + val[i]|dp[i][w] + val[i]|dp[i + 1][w - wt[i]] + val[i]#重さ wt[i] ぶん軽い状態に val[i] を足す⟧);",
   "    }",
   "}",
   "cout << dp[N][W] << endl;"],
   "sw":[],"wr":[2,3,4],"pz":true,
   "bug":[[3,"        dp[i + 1][w] = 0;","選ばない場合の値を引き継がないと、結果が消える"],
          [2,"    for (int w = 0; w < W; w++) {","w = W の場合を計算しないので、答えの dp[N][W] が埋まらない"],
          [4,"        if (w > wt[i]) dp[i + 1][w] = max(dp[i + 1][w], dp[i][w - wt[i]] + val[i]);","w == wt[i] のときも選べる"]]}}
]},
{"id":"unionfind","name":"Union-Find","lv":2,"parts":[
 {"id":"find","name":"find (経路圧縮)","desc":"x の根を探しながら、通った頂点を根に直接つなぎ直す。par[x] == x なら x が根。",
  "py":{"lines":[
   "def find(x):",
   "    if par[x] != x:",
   "        par[x] = ⟦find(par[x])|par[x]|find(x)|x#親の根を探し、その根に直接つなぎ直す⟧",
   "    return par[x]"],
   "sw":[],"wr":[1,2],"pz":true,
   "bug":[[1,"    if par[x] == x:","根でない (par[x] != x) ときにたどる"],
          [2,"        par[x] = find(x)","自分自身を探し続けて終わらない"]]},
  "cpp":{"lines":[
   "int find(int x) {",
   "    if (par[x] != x) par[x] = ⟦find(par[x])|par[x]|find(x)#親の根を探し、その根に直接つなぎ直す⟧;",
   "    return par[x];",
   "}"],
   "sw":[],"wr":[1,2],"pz":true,
   "bug":[[1,"    if (par[x] == x) par[x] = find(par[x]);","根でない (par[x] != x) ときにたどる"]]}},
 {"id":"unite","name":"unite (サイズで合体)","desc":"a と b のグループを合体する。木が深くならないよう、小さい方を大きい方の下につなぐ。",
  "py":{"lines":[
   "def unite(a, b):",
   "    a, b = find(a), find(b)",
   "    if a == b:",
   "        return",
   "    if size[a] ⟦<|>|<=|==#a を大きい方にしたいので、a の方が小さければ入れ替える⟧ size[b]:",
   "        a, b = b, a",
   "    par[⟦b|a#小さい方 b の親を a にする⟧] = a",
   "    size[a] += size[b]"],
   "sw":[[6,7]],"wr":[1,4,6],"pz":true,
   "bug":[[1,"    a, b = par[a], par[b]","親ではなく根どうしをつながないと、グループが正しく合体しない"],
          [6,"    par[a] = b","大きい方 a を小さい方 b の下につなぐと、木が深くなりサイズの記録も狂う"]]},
  "cpp":{"lines":[
   "void unite(int a, int b) {",
   "    a = find(a), b = find(b);",
   "    if (a == b) return;",
   "    if (sz[a] ⟦<|>|==#a を大きい方にしたいので、小さければ入れ替える⟧ sz[b]) swap(a, b);",
   "    par[b] = a;",
   "    sz[a] += sz[b];",
   "}"],
   "sw":[[4,5]],"wr":[1,3,4],"pz":true,
   "bug":[[1,"    a = par[a], b = par[b];","根どうしをつなぐ"],
          [4,"    par[a] = b;","大きい方を小さい方の下につなぐと、木が深くなりサイズの記録も狂う"]]}}
]},
{"id":"dijkstra","name":"ダイクストラ法","lv":2,"parts":[
 {"id":"main","name":"ダイクストラ法","desc":"重みが 0 以上のグラフで、s から各頂点への最短距離を求める。G[v] は (行き先, 重み) のリスト。",
  "py":{"lines":[
   "dist = [INF] * N",
   "dist[s] = 0",
   "pq = [(0, s)]",
   "while pq:",
   "    d, v = heapq.heappop(pq)",
   "    if d ⟦>|>=|==#取り出した距離が、すでに分かっている最短より長ければ古い候補なので捨てる。= を含めると最新の候補まで捨ててしまう⟧ dist[v]:",
   "        continue",
   "    for to, w in G[v]:",
   "        if dist[v] + w < dist[to]:",
   "            dist[to] = dist[v] + w",
   "            heapq.heappush(pq, ⟦(dist[to], to)|(to, dist[to])|dist[to]#距離を先に置くと、距離の小さい順に取り出せる⟧)"],
   "sw":[[1,2]],"wr":[5,8,10],"pz":true,
   "bug":[[5,"    if d >= dist[v]:","d == dist[v] は最新の候補。>= だと、確定させるべき候補まで捨ててしまう"],
          [8,"        if dist[v] + w > dist[to]:","短くなるときだけ更新する"],
          [10,"            heapq.heappush(pq, (to, dist[to]))","タプルは先頭から比べられる。頂点番号が先だと距離の小さい順にならない"]]},
  "cpp":{"lines":[
   "vector<long long> dist(N, INF);",
   "priority_queue<pair<long long, int>, vector<pair<long long, int>>, ⟦greater<>|less<>#距離の小さい順に取り出すので greater。less<> (大きい順) でも答えは出るが、何度も更新し直すことになり非常に遅くなる⟧> pq;",
   "dist[s] = 0;",
   "pq.push({0, s});",
   "while (!pq.empty()) {",
   "    auto [d, v] = pq.top();",
   "    pq.pop();",
   "    if (d ⟦>|>=|==#古い候補 (d > dist[v]) だけを捨てる。= を含めると最新の候補まで捨ててしまう⟧ dist[v]) continue;",
   "    for (auto [to, w] : G[v]) {",
   "        if (dist[v] + w < dist[to]) {",
   "            dist[to] = dist[v] + w;",
   "            pq.push({⟦dist[to], to|to, dist[to]#距離を先に置くと、距離の小さい順に並ぶ⟧});",
   "        }",
   "    }",
   "}"],
   "sw":[[1,2]],"wr":[7,9,11],"pz":true,
   "bug":[[1,"priority_queue<pair<long long, int>> pq;","そのままだと大きい順に取り出される。答えは出ても何度も更新し直すことになり、非常に遅くなる (TLE)。greater<> で小さい順にする"],
          [7,"    if (d >= dist[v]) continue;","d == dist[v] は最新の候補。>= だと確定させるべき候補まで捨ててしまう"],
          [11,"            pq.push({to, dist[to]});","距離を先に置かないと、距離の小さい順にならない"]]}}
]},
{"id":"greedy","name":"貪欲法とソート","lv":2,"parts":[
 {"id":"main","name":"区間スケジューリング","desc":"区間 [l, r) のリスト iv から、重ならないようにできるだけ多く選ぶ (端が接するのはよい)。",
  "py":{"lines":[
   "iv.sort(key=lambda p: ⟦p[1]|p[0]|p[1] - p[0]|-p[1]#終わりが早い順に見ると、残りの時間を最も多く残せる⟧)",
   "cnt = 0",
   "last = -INF",
   "for l, r in iv:",
   "    if l ⟦>=|>|<=|<#前に選んだ区間の終わり以降に始まるなら選べる (端が接するのはよい)⟧ last:",
   "        cnt += 1",
   "        last = ⟦r|l|r - l#選んだ区間の終わりを覚える⟧",
   "print(cnt)"],
   "sw":[[1,2],[5,6]],"wr":[0,4,6],"pz":true,
   "bug":[[0,"iv.sort(key=lambda p: p[0])","始まりが早い順だと、長い区間を先に取って損をすることがある"],
          [4,"    if l > last:","端が接する (l == last) 区間も選べる"],
          [6,"        last = l","次の区間は、選んだ区間の終わり r 以降でないと重なる"]]},
  "cpp":{"lines":[
   "sort(iv.begin(), iv.end(), [](auto& a, auto& b) { return ⟦a.second < b.second|a.first < b.first|a.second > b.second#終わりが早い順に並べる⟧; });",
   "int cnt = 0;",
   "long long last = -INF;",
   "for (auto [l, r] : iv) {",
   "    if (l ⟦>=|>|<=#端が接するのはよい⟧ last) {",
   "        cnt++;",
   "        last = r;",
   "    }",
   "}"],
   "sw":[[1,2],[5,6]],"wr":[4,6],"pz":true,
   "bug":[[0,"sort(iv.begin(), iv.end());","そのままだと始まり (first) の順になる。終わりの順に並べる"],
          [6,"        last = l;","選んだ区間の終わり r を覚える"]]}}
]},
{"id":"math","name":"整数論の道具","lv":2,"parts":[
 {"id":"modpow","name":"繰り返し二乗法","desc":"a^b mod m を O(log b) で求める (Python なら組み込みの pow(a, b, m) でもよい)。",
  "py":{"lines":[
   "def modpow(a, b, m):",
   "    res = 1",
   "    a %= m",
   "    while b > 0:",
   "        if ⟦b & 1|b % 2 == 0|b > 1|b & 2#b の一番下のビットが 1 なら、今の a を掛ける⟧:",
   "            res = res * a % m",
   "        a = ⟦a * a % m|a * 2 % m|a * res % m#a を 2 乗して、次のビットに対応させる⟧",
   "        b ⟦>>=|<<=|-=#b を 1 ビット右にずらす⟧ 1",
   "    return res"],
   "sw":[[1,2]],"wr":[4,6,7],"pz":true,
   "bug":[[4,"        if b % 2 == 0:","掛けるのはビットが 1 (b が奇数) のとき"],
          [6,"        a = a * 2 % m","次のビットに対応するのは a の 2 乗"],
          [7,"        b <<= 1","左にずらすと b が増え続けて終わらない"]]},
  "cpp":{"lines":[
   "long long modpow(long long a, long long b, long long m) {",
   "    long long res = 1;",
   "    a %= m;",
   "    while (b > 0) {",
   "        if (⟦b & 1|b % 2 == 0|b > 1#一番下のビットが 1 なら掛ける⟧) res = res * a % m;",
   "        a = ⟦a * a % m|a * 2 % m|a * a#2 乗して mod を取る⟧;",
   "        b >>= 1;",
   "    }",
   "    return res;",
   "}"],
   "sw":[[1,2]],"wr":[4,5,6],"pz":true,
   "bug":[[4,"        if (b % 2 == 0) res = res * a % m;","掛けるのは b が奇数のとき"],
          [5,"        a = a * a;","mod を取らないと、すぐに long long の範囲を超える"]]}},
 {"id":"sieve","name":"エラトステネスの篩","desc":"N 以下の整数が素数かどうかを、まとめて求める (Python は from math import isqrt)。",
  "py":{"lines":[
   "is_p = [True] * (N + 1)",
   "is_p[0] = is_p[1] = False",
   "for i in range(2, isqrt(N) + 1):",
   "    if is_p[i]:",
   "        for j in range(⟦i * i|i|i + 1|1#i * i より小さい i の倍数は、もっと小さい素数ですでに消えている。i から始めると素数 i 自身を消してしまう⟧, N + 1, i):",
   "            is_p[j] = ⟦False|True|not is_p[j]#i の倍数は素数ではない⟧"],
   "sw":[],"wr":[3,4,5],"pz":true,
   "bug":[[4,"        for j in range(i, N + 1, i):","i から始めると、素数 i 自身も消してしまう"],
          [3,"    if not is_p[i]:","倍数を消すのは、i が素数のとき"]]},
  "cpp":{"lines":[
   "vector<bool> is_p(N + 1, true);",
   "is_p[0] = is_p[1] = false;",
   "for (long long i = 2; i * i <= N; i++) {",
   "    if (!is_p[i]) continue;",
   "    for (long long j = ⟦i * i|i|i + 1#i * i より小さい倍数はすでに消えている。i からだと i 自身を消してしまう⟧; j <= N; j += i) is_p[j] = false;",
   "}"],
   "sw":[],"wr":[3,4],"pz":true,
   "bug":[[3,"    if (is_p[i]) continue;","飛ばすのは素数でない i"],
          [4,"    for (long long j = i; j <= N; j += i) is_p[j] = false;","i から始めると、素数 i 自身も消してしまう"]]}}
]},
{"id":"segtree","name":"セグメント木","lv":3,"parts":[
 {"id":"update","name":"一点更新","desc":"葉 i の値を x にして、根まで区間の和を更新する。葉は seg[size] から並ぶ (下から作るセグメント木)。",
  "py":{"lines":[
   "def update(i, x):",
   "    i += ⟦size|1|N#葉は seg[size] から並んでいる⟧",
   "    seg[i] = x",
   "    while i > 1:",
   "        i ⟦//=|-=|*=#親の番号は i // 2⟧ 2",
   "        seg[i] = ⟦seg[2 * i] + seg[2 * i + 1]|seg[i] + x|seg[2 * i]|seg[i - 1] + seg[i + 1]#子 2 つの和で作り直す⟧"],
   "sw":[],"wr":[1,4,5],"pz":true,
   "bug":[[5,"        seg[i] = seg[i] + x","更新前の値が残ってしまう。子 2 つの和で作り直す"],
          [1,"    i += 1","葉は seg[size] から。1 足すだけでは内部の節点を書き換えてしまう"]]},
  "cpp":{"lines":[
   "void update(int i, long long x) {",
   "    i += ⟦sz|1|N#葉は seg[sz] から並んでいる⟧;",
   "    seg[i] = x;",
   "    while (i > 1) {",
   "        i /= 2;",
   "        seg[i] = ⟦seg[2 * i] + seg[2 * i + 1]|seg[i] + x|seg[2 * i]#子 2 つの和で作り直す⟧;",
   "    }",
   "}"],
   "sw":[],"wr":[1,4,5],"pz":true,
   "bug":[[5,"        seg[i] = seg[i] + x;","更新前の値が残ってしまう"],
          [1,"    i += 1;","葉は seg[sz] から並んでいる"]]}},
 {"id":"query","name":"区間の和","desc":"[l, r) の和を、左右の端から上へのぼりながら求める。",
  "py":{"lines":[
   "def query(l, r):",
   "    res = 0",
   "    l += size",
   "    r += size",
   "    while l < r:",
   "        if ⟦l & 1|l % 2 == 0|r & 1#l が右の子 (奇数) なら、その節点を足して右へ進む⟧:",
   "            res += seg[l]",
   "            l += 1",
   "        if r & 1:",
   "            r ⟦-= 1|+= 1#r は開区間の端。先に 1 減らしてから足す⟧",
   "            res += seg[r]",
   "        l //= 2",
   "        r //= 2",
   "    return res"],
   "sw":[[1,2,3],[11,12]],"wr":[5,9],"pz":false,
   "bug":[[9,"            r += 1","r は開区間の端。1 減らしてから seg[r] を足す"],
          [7,"            l -= 1","左端は足したら右 (l + 1) へ進む"]]},
  "cpp":{"lines":[
   "long long query(int l, int r) {",
   "    long long res = 0;",
   "    for (l += sz, r += sz; l < r; l /= 2, r /= 2) {",
   "        if (⟦l & 1|r & 1|l % 2 == 0#l が右の子 (奇数) なら足して右へ⟧) res += seg[l++];",
   "        if (r & 1) res += seg[⟦--r|r--|r#先に 1 減らしてから足す⟧];",
   "    }",
   "    return res;",
   "}"],
   "sw":[[3,4]],"wr":[3,4],"pz":true,
   "bug":[[4,"        if (r & 1) res += seg[r--];","r は開区間の端。r-- だと範囲外の seg[r] を足してしまう"],
          [2,"    for (l += sz, r += sz; l <= r; l /= 2, r /= 2) {","[l, r) は半開区間。l == r なら空なので l < r"]]}}
]},
{"id":"doubling","name":"ダブリング","lv":3,"parts":[
 {"id":"build","name":"表を作る","desc":"nxt[k][v] = 「v から 2^k 回進んだ先」の表を作る。A[v] が 1 回進んだ先。",
  "py":{"lines":[
   "nxt = [A[:]]",
   "for k in range(LOG - 1):",
   "    prev = nxt[-1]",
   "    nxt.append([⟦prev[prev[v]]|prev[v]|A[prev[v]]|A[A[v]]#2^k 回進んでから、さらに 2^k 回進むと 2^(k+1) 回⟧ for v in range(N)])"],
   "sw":[],"wr":[3],"pz":true,
   "bug":[[3,"    nxt.append([A[prev[v]] for v in range(N)])","A[...] は 1 回しか進まない。2^k + 1 回になってしまう"]]},
  "cpp":{"lines":[
   "vector<vector<int>> nxt(LOG, vector<int>(N));",
   "nxt[0] = A;",
   "for (int k = 0; k + 1 < LOG; k++)",
   "    for (int v = 0; v < N; v++)",
   "        nxt[k + 1][v] = ⟦nxt[k][nxt[k][v]]|nxt[k][v]|A[nxt[k][v]]#2^k 回を 2 度進むと 2^(k+1) 回⟧;"],
   "sw":[],"wr":[4],"pz":true,
   "bug":[[4,"        nxt[k + 1][v] = A[nxt[k][v]];","A[...] は 1 回しか進まない"]]}},
 {"id":"jump","name":"K 回先へ跳ぶ","desc":"s から K 回進んだ先を、K を 2 進数に分けて O(log K) で求める。",
  "py":{"lines":[
   "v = s",
   "for k in range(LOG):",
   "    if ⟦K >> k & 1|K & k|K >> k|k >> K & 1#K の k ビット目が 1 なら、2^k 回進む⟧:",
   "        v = nxt[k][⟦v|s|k#今いる v から進む⟧]",
   "print(v)"],
   "sw":[],"wr":[2,3],"pz":true,
   "bug":[[2,"    if K & k:","k ビット目を見るのは K >> k & 1"],
          [3,"        v = nxt[k][s]","進むのは、今いる v から"]]},
  "cpp":{"lines":[
   "int v = s;",
   "for (int k = 0; k < LOG; k++) {",
   "    if (⟦K >> k & 1|K & k|K >> k#K の k ビット目が 1 なら 2^k 回進む⟧) v = nxt[k][v];",
   "}",
   "cout << v << endl;"],
   "sw":[],"wr":[2],"pz":true,
   "bug":[[2,"    if (K & k) v = nxt[k][v];","K の k ビット目を見るのは K >> k & 1"]]}}
]}
]};
